// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNr3_zbuo4c5grNVgh0nN3saAOI0FDXH4',
    appId: '1:735124461824:web:5b5ff38a27abab92ebfbe5',
    messagingSenderId: '735124461824',
    projectId: 'haan-r-haan',
    authDomain: 'haan-r-haan.firebaseapp.com',
    storageBucket: 'haan-r-haan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGT6vsZpEHhSDy4phm7aEjOUtrlAugTc',
    appId: '1:735124461824:android:6ad0843d1e7f9311ebfbe5',
    messagingSenderId: '735124461824',
    projectId: 'haan-r-haan',
    storageBucket: 'haan-r-haan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATlrc5YwfeIOn6oFTvi4aJn8EEr647s2I',
    appId: '1:735124461824:ios:627fa4d5b4d6807eebfbe5',
    messagingSenderId: '735124461824',
    projectId: 'haan-r-haan',
    storageBucket: 'haan-r-haan.appspot.com',
    iosClientId: '735124461824-bfhm5ibfck1jpurmv53ud8tjjsl36s8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.haanRHaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATlrc5YwfeIOn6oFTvi4aJn8EEr647s2I',
    appId: '1:735124461824:ios:627fa4d5b4d6807eebfbe5',
    messagingSenderId: '735124461824',
    projectId: 'haan-r-haan',
    storageBucket: 'haan-r-haan.appspot.com',
    iosClientId: '735124461824-bfhm5ibfck1jpurmv53ud8tjjsl36s8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.haanRHaan',
  );
}
